In [1]:
import requests
import time
from bs4 import BeautifulSoup
from random import sample 
import re
import glob as gb
import pandas as pd 
import shutil as sh
import os
import json
import csv
from datetime import datetime

In [2]:
path = "C:\\Users\\padu\\Desktop\\ResearchCollab\\Tonaton\\Rentals"
os.chdir(path)

In [3]:
All1 = gb.glob(path + "/TonatonRentals*.csv")
All2 = gb.glob(path + "/TonatonRentalsAshanti*.csv")
diff = set(All1).difference(set(All2))
All = list(diff)

In [4]:
Tonaton = (pd.read_csv(file) for file in All)
Tonaton  = pd.concat(Tonaton, ignore_index=True)

In [5]:
Tonaton.columns

Index(['Title', 'price', 'description', 'Landmark', 'Size', 'Beds', 'Baths',
       'URL'],
      dtype='object')

In [6]:
# Tonaton.drop('Unnamed: 0',axis = 1, inplace = True)

In [7]:
Tonaton.columns

Index(['Title', 'price', 'description', 'Landmark', 'Size', 'Beds', 'Baths',
       'URL'],
      dtype='object')

In [8]:
Tonaton

,Title,price,description,Landmark,Size,Beds,Baths,URL
0,"<h1 class=""title--3s1R8"">Fully Furnished One b...","7,000 /month",This fully furnished one bedroom apartment is ...,[],['100.0 mÂ²'],1,1,https://tonaton.com/en/ad/fully-furnished-one-...
1,"<h1 class=""title--3s1R8"">Fully Furnished one b...","7,500 /month",This fully furnished one bedroom apartment is ...,[],['100.0 mÂ²'],1,2,https://tonaton.com/en/ad/fully-furnished-one-...
2,Newly Built 2 Bedrooms Apartment For Rent east...,"2,200 /month",2 bedrooms newly built for rent at east legon ...,East Legon Hills,"1,000.0 mÂ²",2,2,https://tonaton.com/en/ad/newly-built-2-bedroo...
3,"Executive 2 bedroom apartment in Osu, Accra","9,350 /month",An executive two bedroom apartment to let at O...,Labone Junction,75.0 mÂ²,2,2,https://tonaton.com/en/ad/executive-2-bedroom-...
4,2 bedrooms apartments all en-suite at east leg...,"3,000 /month",2 bedrooms apartments all en-suite at east leg...,AnC Mall,"1,000.0 mÂ²",2,3,https://tonaton.com/en/ad/2-bedrooms-apartment...
...,...,...,...,...,...,...,...,...
35627,SINGLE SELF CONT. FOR RENT @ SANTA MARIA A LANG,350 /month,DetailsBedroom=1Loc=santa maria A LANGpricr=gh...,SANTA MARIA ( A LANG),100.0 sqft,1,1,https://tonaton.com/en/ad/single-self-cont-for...
35628,2 BEDROOMS APARTMENT FOR RENT @ AMASAMAN ASALAJA,600 /month,DetailsBedrooms=2Washroom=1Loc=asamana asalaja...,AMASAMAN ASALAJA,100.0 mÂ²,2,1,https://tonaton.com/en/ad/2-bedrooms-apartment...
35629,NEWLY BUILT SINGLE ROOM SC FOR RENT@ADENTA,400 /month,WALL N GATEDWATER FLOWSNICE ENVIRONMENTP. O. P...,ADENTA BARRIER,100.0 sqft,1,1,https://tonaton.com/en/ad/newly-built-single-r...
35630,2 bedrooms apartment at nsawam new road.,550 /month,"Nice executive apartment at nsawam for rent ,s...",around nsawam new road.,15.0 sqft,2,2,https://tonaton.com/en/ad/2-bedrooms-apartment...
35631,Newly built 2 bedroom apartment for rent Foste...,"1,300 /month","Newly built, self meter, walled and gated, wat...",Foster Home,"2,500.0 mÂ²",2,2,https://tonaton.com/en/ad/newly-built-2-bedroo...

In [9]:
Tonaton['Beds'] = [text.strip("Beds:") for text in Tonaton['Beds']]
Tonaton['Baths'] = [text.strip("Baths:") for text in Tonaton['Baths']]
Tonaton['Title'] = [text.lower() for text in Tonaton['Title']]
Tonaton['Landmark'] = [str(text).replace("Street / Landmark:","") for text in Tonaton['Landmark']]
Tonaton['price'] = [text.strip("GHâµ") for text in Tonaton['price']]
Tonaton['Title'] = [BeautifulSoup(row,'html.parser').get_text().rstrip('\n\n').strip() for row in Tonaton['Title']]

In [10]:
Tonaton.drop_duplicates(subset = 'description', inplace = True)

In [11]:
Tonaton.drop_duplicates(subset = "Title", inplace = True)

In [12]:
Tonaton.shape

(6212, 8)

In [13]:
path = "C:\\Users\\padu\\Desktop\\ResearchCollab\\Tonaton\\Final"
os.chdir(path)

In [14]:
Tonaton.to_csv("TonatonFinalRentals2021.csv",index= False)

In [15]:
path = "C:\\Users\\padu\\Desktop\\ResearchCollab\\Tonaton\\Rentals"
os.chdir(path)

In [16]:
All = gb.glob(path + "/TonatonRentalsAshanti*.csv")
# All

In [17]:
TonatonAsh = (pd.read_csv(file) for file in All)
TonatonAshanti  = pd.concat(TonatonAsh, ignore_index=True)

In [18]:
TonatonAshanti

,Title,price,description,Landmark,Size,Beds,Baths,URL
0,Three bed room flat at Asuoyeboa for rent,900 /month,"Wall and gated, all the rooms are tiled and sp...",Kumasi,10.0 mÂ²,3,2,https://tonaton.com/en/ad/three-bed-room-flat-...
1,Chamber and hall self Contain at Medoma-80's f...,250 /month,"Wall and gated, all the rooms are Spacious and...",Kumasi,10.0 mÂ²,1,1,https://tonaton.com/en/ad/chamber-and-hall-sel...
2,Single room self contained at Atimatim-Taabuo ...,250 /month,"Wall and gated, the room is spacious and tiled...",Atimatim-Taabuo,10.0 mÂ²,1,1,https://tonaton.com/en/ad/single-room-self-con...
3,Executive 2 bedrooms apt Atonsu Feyiase - 1 year,700 /month,This newly built executive apartment is availa...,Atonsu Feyiase lake road-Kumasi,300.0 mÂ²,2,2,https://tonaton.com/en/ad/executive-2-bedrooms...
4,3 Bedrooms Flat @ Tech Apemso KNUST Campus,"1,000 /month",3 Bedrooms Flat @ Tech Apemso KNUST Campus 2 y...,Tech Apemso KNUST Campus,100.0 mÂ²,3,2,https://tonaton.com/en/ad/3-bedrooms-flat-tech...
...,...,...,...,...,...,...,...,...
2082,apartment in kotei,900 /month,Three bedrooms three toilets and bath and big ...,kotei,90.0 mÂ²,3,3,https://tonaton.com/en/ad/apartment-in-kotei-f...
2083,Two bedroom flat at Ahodwo-Sokoban for rent.,600 /month,"Water and electricity is available, all the ro...",Kumasi,10.0 mÂ²,2,2,https://tonaton.com/en/ad/two-bedroom-flat-at-...
2084,Two bedroom flat at Ahodwo-T.U.C for rent,"1,500 /month","Two bedroom flat at T. U. C. Wall and gated, a...",Kumasi,10.0 mÂ²,2,3,https://tonaton.com/en/ad/two-bedroom-flat-at-...
2085,Executive three bedroom at Esreso,"1,000 /month",Three bedroomAll room ensuiteLiving roomKitchen,Esreso,100.0 mÂ²,3,3,https://tonaton.com/en/ad/executive-three-bedr...
2086,Three Separate rooms at IPT for rent,400 /month,"Wall and gated, all the rooms are spacious and...",Kumasi,10.0 mÂ²,3,1,https://tonaton.com/en/ad/three-separate-rooms...

In [19]:
TonatonAshanti.drop_duplicates(subset = 'description', inplace = True)

In [20]:
TonatonAshanti.drop_duplicates(subset = "Title", inplace = True)

In [21]:
TonatonAshanti

,Title,price,description,Landmark,Size,Beds,Baths,URL
0,Three bed room flat at Asuoyeboa for rent,900 /month,"Wall and gated, all the rooms are tiled and sp...",Kumasi,10.0 mÂ²,3,2,https://tonaton.com/en/ad/three-bed-room-flat-...
1,Chamber and hall self Contain at Medoma-80's f...,250 /month,"Wall and gated, all the rooms are Spacious and...",Kumasi,10.0 mÂ²,1,1,https://tonaton.com/en/ad/chamber-and-hall-sel...
2,Single room self contained at Atimatim-Taabuo ...,250 /month,"Wall and gated, the room is spacious and tiled...",Atimatim-Taabuo,10.0 mÂ²,1,1,https://tonaton.com/en/ad/single-room-self-con...
3,Executive 2 bedrooms apt Atonsu Feyiase - 1 year,700 /month,This newly built executive apartment is availa...,Atonsu Feyiase lake road-Kumasi,300.0 mÂ²,2,2,https://tonaton.com/en/ad/executive-2-bedrooms...
4,3 Bedrooms Flat @ Tech Apemso KNUST Campus,"1,000 /month",3 Bedrooms Flat @ Tech Apemso KNUST Campus 2 y...,Tech Apemso KNUST Campus,100.0 mÂ²,3,2,https://tonaton.com/en/ad/3-bedrooms-flat-tech...
...,...,...,...,...,...,...,...,...
1781,Affordable 2 Bedrooms Flat @ Tech Kotei Newsite,400 /month,2 years advanceInspection fee is 70 cedis Comm...,Tech Kotei Newsite,100.0 sqft,2,1,https://tonaton.com/en/ad/affordable-2-bedroom...
1784,2 bedroom Self contained Ejisu-Tech,400 /month,"2 bedroom Self contained, separate meter, Clos...",Royal Basin,100.0 sqft,1,1,https://tonaton.com/en/ad/2-bedroom-self-conta...
1785,New chamber and hall at Daban Site near Atasom...,500 /month,This is a nice newly built chamber and hall ap...,Daban New Site near Atasomanso,200.0 sqft,1,1,https://tonaton.com/en/ad/new-chamber-and-hall...
1786,Newly built 3 bedrooms apartment at Daban New ...,"1,500 /month",This is a newly built executive 3 bedrooms apa...,Daban New Site near Atasomanso residential,200.0 sqft,3,2,https://tonaton.com/en/ad/newly-built-3-bedroo...
1932,Chamber and hall self contained at Tech-Bomso,667 /month,"Wall and gated, gated, self meter, the rooms a...",Bomso,10.0 mÂ²,1,1,https://tonaton.com/en/ad/chamber-and-hall-sel...

In [22]:
# TonatonAshanti.drop_duplicates(subset = ["Title", 'description'], inplace = True)

In [23]:
TonatonAshanti['Beds'] = [str(text).strip("Beds:") for text in TonatonAshanti['Beds']]
TonatonAshanti['Baths'] = [str(text).strip("Baths:") for text in TonatonAshanti['Baths']]
TonatonAshanti['Title'] = [text.lower() for text in TonatonAshanti['Title']]
TonatonAshanti['Landmark'] = [str(text).replace("Street / Landmark:","") for text in TonatonAshanti['Landmark']]
TonatonAshanti['price'] = [text.strip("GHâµ") for text in TonatonAshanti['price']]
TonatonAshanti['Title'] = ([BeautifulSoup(row,'html.parser').get_text().rstrip('\n\n').strip() 
                            for row in TonatonAshanti['Title']])

In [24]:
path = "C:\\Users\\padu\\Desktop\\ResearchCollab\\Tonaton\\Final"
os.chdir(path)

In [25]:
TonatonAshanti.to_csv("TonatonRentalsiFinal.csv",index= False)

In [26]:
TonatonAshanti.shape

(424, 8)